---
# Initial Server Setup
#remote_user: root
remote_user: root

# MySQL Setup
mysql_app_user: dinhlongit
mysql_app_pass: Aa@123456
mysql_root_user: root
mysql_root_password: Aa@123456
mysql_app_db: savenote

# Web Server Setup
http_host: "{{ ansible_facts.eth0.ipv4.address }}"
#server_name: savenote.online  www.savenote.online
server_name: localhost
remote_www_root: /var/www/html
app_root_dir: savenote
document_root: "{{ remote_www_root }}/{{ app_root_dir }}/public"

# Laravel Env Variables
app_name: SAVENOTE
app_env: prod
app_debug: true
app_url: "http://{{ http_host }}"
db_host: localhost
db_port: 3306
db_database: "{{ mysql_app_db }}"
db_user: "{{ mysql_app_user }}"
db_pass: "{{ mysql_app_pass }}"