---
- name: Install pip3
  apt: name={{ item }} update_cache=yes state=latest
  ignore_errors: yes
  with_items:
    - python3-pip

- name: Install Mysql & mysql-python prereq
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - mysql-server
    - python3-mysqldb

- name: Install the MySQL-python through pip
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
    - MySQL-python

# Mysql Configuration
- name: Sets the root password
  mysql_user:
    name: root
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: localhost
  no_log: false

- name: Removes the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: test
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock


- name: Create new MySQL user for the application.
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_pass }}"
    priv: "{{ mysql_app_db }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    state: present

- name: Creates App Database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_app_db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
