---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install Main PHP Packages
  apt: name={{ item }} update_cache=yes
  loop: [ 'php-fpm', 'php-mysql' ]

- name: Install PHP Modules / Extensions
  apt: name={{ item }} update_cache=yes
  loop: "{{ php_packages }}"